**1. Import the numpy package under the name `np`**

In [2]:
import numpy as np

**2. Print the numpy version and the configuration**

In [3]:
np.__version__

'1.21.5'

**3. Create a null vector of size 10**

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**4. How to find the memory size of any array**

In [12]:
arr = np.random.random((5, 5))

arr.size * arr.itemsize

200

**5. How to get the documentation of the numpy add function from the command line?**

In [15]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**6. Create a null vector of size 10 but the fifth value which is 1**

In [17]:
vec = np.zeros(10)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
vec[4] = 1
vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**7. Create a vector with values ranging from 10 to 49**

In [19]:
vec = np.arange(10, 50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**8. Reverse a vector (first element becomes last)**

In [21]:
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
vec[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**9. Create a 3x3 matrix with values ranging from 0 to 8**

In [24]:
mt = np.arange(0, 9).reshape(3, 3)
mt

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**10. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [26]:
arr = [1,2,0,0,4,0]

np.nonzero(arr)

(array([0, 1, 4]),)

**11. Create a 3x3 identity matrix**

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**12. Create a 3x3x3 array with random values**

In [28]:
np.random.random((3, 3))

array([[0.78426832, 0.21463335, 0.31760393],
       [0.60007415, 0.3677032 , 0.36516903],
       [0.271287  , 0.77799834, 0.75685986]])

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [38]:
arr = np.random.random((10, 10))

print(np.min(arr))
print(np.max(arr))

0.004272832608436472
0.9890157737221836


**14. Create a random vector of size 30 and find the mean value**

In [41]:
vec = np.random.random(30)
np.mean(vec)

0.5647604668880228

**15. Create a 2d array with 1 on the border and 0 inside**

In [59]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0

arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**16. How to add a border (filled with 0's) around an existing array?**

In [83]:
arr = np.ones((5, 5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
np.pad(arr, 1, 'constant', constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**17. What is the result of the following expression?**  

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [85]:
0 * np.nan

nan

In [86]:
np.nan == np.nan

False

In [87]:
np.inf > np.nan

False

In [88]:
np.nan - np.nan

nan

In [89]:
np.nan in set([np.nan])

True

In [90]:
0.3 == 3 * 0.1

False

**18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [92]:
np.diag([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**19. Create a 8x8 matrix and fill it with a checkerboard pattern**

In [107]:
arr = np.zeros((8, 8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [115]:
arr = np.zeros((8, 8))
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?**

In [124]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)