**1. Import the numpy package under the name `np`**

In [1]:
import numpy as np

**2. Print the numpy version and the configuration**

In [2]:
np.__version__

'1.21.5'

**3. Create a null vector of size 10**

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**4. How to find the memory size of any array**

In [4]:
arr = np.random.random((5, 5))

arr.size * arr.itemsize

200

**5. How to get the documentation of the numpy add function from the command line?**

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**6. Create a null vector of size 10 but the fifth value which is 1**

In [6]:
vec = np.zeros(10)
vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
vec[4] = 1
vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**7. Create a vector with values ranging from 10 to 49**

In [8]:
vec = np.arange(10, 50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**8. Reverse a vector (first element becomes last)**

In [9]:
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
vec[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**9. Create a 3x3 matrix with values ranging from 0 to 8**

In [11]:
mt = np.arange(0, 9).reshape(3, 3)
mt

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**10. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [12]:
arr = [1,2,0,0,4,0]

np.nonzero(arr)

(array([0, 1, 4]),)

**11. Create a 3x3 identity matrix**

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**12. Create a 3x3x3 array with random values**

In [14]:
np.random.random((3, 3))

array([[0.85800634, 0.88270755, 0.35960213],
       [0.23700001, 0.8732227 , 0.34890082],
       [0.05911976, 0.45521636, 0.63647907]])

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [15]:
arr = np.random.random((10, 10))

print(np.min(arr))
print(np.max(arr))

0.0024979523955839245
0.9916276745881263


**14. Create a random vector of size 30 and find the mean value**

In [16]:
vec = np.random.random(30)
np.mean(vec)

0.47308649560612986

**15. Create a 2d array with 1 on the border and 0 inside**

In [17]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0

arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**16. How to add a border (filled with 0's) around an existing array?**

In [18]:
arr = np.ones((5, 5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.pad(arr, 1, 'constant', constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**17. What is the result of the following expression?**  

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [20]:
0 * np.nan

nan

In [21]:
np.nan == np.nan

False

In [22]:
np.inf > np.nan

False

In [23]:
np.nan - np.nan

nan

In [24]:
np.nan in set([np.nan])

True

In [25]:
0.3 == 3 * 0.1

False

**18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [26]:
np.diag([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**19. Create a 8x8 matrix and fill it with a checkerboard pattern**

In [27]:
arr = np.zeros((8, 8))
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?**

In [28]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

**21. Create a checkerboard 8x8 matrix using the tile function**

In [29]:
arr = np.zeros((2, 8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
arr[0, 1::2] = 1
arr[1, ::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [31]:
np.tile(arr, (4,1))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**22. Normalize a 5x5 random matrix**

In [32]:
mt = np.random.randint(1, 100, (5, 5))
mt

array([[ 7, 97, 37, 25, 69],
       [61, 73, 41, 84, 67],
       [30, 36, 69, 54, 73],
       [57, 38, 43, 37, 78],
       [69, 48, 18, 26, 83]])

In [33]:
normalized = (mt - np.mean(mt)) / np.std(mt)
normalized

array([[-2.01280281,  1.94248656, -0.69437302, -1.22174494,  0.71195209],
       [ 0.36037081,  0.88774272, -0.51858238,  1.37116698,  0.62405677],
       [-1.00200664, -0.73832068,  0.71195209,  0.05273719,  0.88774272],
       [ 0.18458017, -0.65042536, -0.43068706, -0.69437302,  1.10748102],
       [ 0.71195209, -0.21094877, -1.52937855, -1.17779728,  1.32721932]])

**23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)**

In [34]:
#new_dt = np.dtype([('red', 'ubyte'), ('green', 'ubyte'), ('blue', 'ubyte'), ('alpha', 'ubyte')])

rgba_dt = np.dtype([('red', np.ubyte), ('green', np.ubyte), ('blue', np.ubyte), ('alpha', np.ubyte)])
rgba_dt

dtype([('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')])

In [35]:
red = np.array((255, 0, 0, 1), dtype = rgba_dt)
red

array((255, 0, 0, 1),
      dtype=[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')])

**24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)**

In [36]:
arr1 = np.random.randint(1, 6, (5, 3))
arr2 = np.random.randint(0, 2, (3, 2))

print(f'\narr1:\n {arr1}')
print(f'\narr2:\n {arr2}')

np.dot(arr1, arr2)


arr1:
 [[2 1 3]
 [4 5 3]
 [4 5 3]
 [3 4 1]
 [2 3 5]]

arr2:
 [[1 0]
 [1 1]
 [1 1]]


array([[ 6,  4],
       [12,  8],
       [12,  8],
       [ 8,  5],
       [10,  8]])

**25. Given a 1D array, negate all elements which are between 3 and 8, in place.**

In [37]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[(arr >= 3) & (arr <= 8)] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

**26. What is the output of the following script?**

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [39]:
print(sum(range(5),-1))
#from numpy import *
print(sum(range(5),-1))

9
9


In [43]:
range(5)

range(0, 5)

In [41]:
sum(range(5))

10