**1. Import the numpy package under the name `np`**

In [25]:
import numpy as np

**2. Create a null vector of size 10**

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**3. Create a null vector of size 10 but the fifth value which is 1**

In [27]:
arr = np.zeros(10)
arr[4] = 1

arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**4. Create a vector with values ranging from 10 to 49**

In [28]:
arr = np.arange(10, 50)

arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**5. Create a 3x3 matrix with values ranging from 0 to 8**

In [29]:
arr = np.arange(0, 9)
mt = arr.reshape(3, 3)

mt

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**6. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [30]:
arr = np.array([1,2,0,0,4,0])

np.nonzero(arr)

(array([0, 1, 4]),)

**7. Create a 3x3 identity matrix**

In [31]:
arr = np.eye(3)

arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**8. Create a 3x3x3 array with random values**

In [32]:
arr = np.random.random((3, 3))

arr

array([[0.06792516, 0.84304597, 0.27895386],
       [0.35009425, 0.16942533, 0.89380752],
       [0.5346463 , 0.34028456, 0.40118302]])

**9. Create a 10x10 array with random values and find the minimum and maximum values**

In [33]:
arr = np.random.random((10, 10))

print(np.min(arr))
print(np.max(arr))

0.008119443684053596
0.9974992506891692


**10. Create a random vector of size 30 and find the mean value**

In [34]:
vec = np.random.random(30)

np.mean(vec)

0.4863599028565041

**11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [41]:
np.diag([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**12. Normalize a 5x5 random matrix**

In [54]:
mt = np.random.random((5, 5))

normalized = (mt - np.mean(mt)) / np.std(mt)
normalized2 = (mt - np.min(mt)) / (np.max(mt) - np.min(mt))

print(mt)
print(normalized)
print(normalized2)

[[0.50064137 0.10551689 0.07434226 0.27470224 0.47448077]
 [0.69268602 0.62464915 0.54787585 0.08183426 0.10718352]
 [0.30449152 0.38431687 0.2176732  0.15444701 0.7370975 ]
 [0.6230042  0.2833191  0.76345863 0.93878254 0.59083977]
 [0.78570079 0.21378128 0.36593992 0.99927579 0.15498364]]
[[ 0.2214882  -1.22265078 -1.33659079 -0.60429588  0.1258739 ]
 [ 0.92339146  0.67472376  0.39412531 -1.30920831 -1.2165594 ]
 [-0.49541915 -0.20366578 -0.81273109 -1.04381626  1.08571081]
 [ 0.66871163 -0.57280215  1.18205801  1.82284871  0.55115397]
 [ 1.2633508  -0.82695567 -0.27083164  2.04394526 -1.04185494]]
[[0.46089702 0.03370472 0.         0.21662094 0.43261325]
 [0.66852778 0.59496912 0.51196499 0.00810004 0.03550662]
 [0.24882789 0.33513177 0.1549635  0.08660595 0.71654364]
 [0.59319066 0.22593714 0.74504421 0.93459719 0.55841581]
 [0.76909152 0.15075571 0.31526336 1.         0.08718613]]


**13. How to find common values between two arrays?**

In [55]:
arr1 = np.arange(1, 10)
arr2 = np.arange(5, 15)

np.intersect1d(arr1, arr2)

array([5, 6, 7, 8, 9])

**14. Create a random vector of size 10 and sort it**

In [59]:
vec = np.random.random(10)

np.sort(vec)

array([0.03414026, 0.04231314, 0.37436873, 0.48271383, 0.58542107,
       0.68180135, 0.89148186, 0.91021863, 0.94854585, 0.99526637])

**15. Create random vector of size 10 and replace the maximum value by 0**

In [70]:
vec = np.random.random(10)
vec


array([0.42823226, 0.15537368, 0.74026574, 0.30114167, 0.7158887 ,
       0.82687405, 0.28532199, 0.07485713, 0.81791309, 0.64344663])

In [71]:
vec[np.argmax(vec)] = 0
vec


array([0.42823226, 0.15537368, 0.74026574, 0.30114167, 0.7158887 ,
       0.        , 0.28532199, 0.07485713, 0.81791309, 0.64344663])

**16. Subtract the mean of each row of a matrix**

In [74]:
arr = np.arange(1, 10).reshape(3, 3)

print(arr)
np.mean(arr, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [76]:
mean = np.mean(arr, axis=1, keepdims=True)
print(mean)

[[2.]
 [5.]
 [8.]]


In [77]:
subtracted = arr - mean
subtracted

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

**17. How to get the n largest values of an array**

In [165]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5

In [195]:
#np.sort

sorted = np.sort(arr)

print(sorted[-n:])


[9995 9996 9997 9998 9999]


In [196]:
#np.argsort

sorted_indices = np.argsort(arr)
n_largest = arr[sorted_indices[-n:]]

print(n_largest)


[9995 9996 9997 9998 9999]


In [197]:
#np.argpartition

sorted_indices = np.argpartition(arr, range(len(arr)))
n_largest = arr[sorted_indices[-n:]]

print(n_largest)


[9995 9996 9997 9998 9999]


**18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36)**

In [205]:
mt = np.arange(1, 16).reshape(5, 3)
np.random.shuffle(mt)

mt

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [207]:
np.where(mt <= 4, mt, mt**2)

array([[ 49,  64,  81],
       [100, 121, 144],
       [169, 196, 225],
       [  4,  25,  36],
       [  1,   2,   3]])