**1. Import the numpy package under the name `np`**

In [2]:
import numpy as np

**2. Create a null vector of size 10**

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**3. Create a null vector of size 10 but the fifth value which is 1**

In [4]:
arr = np.zeros(10)
arr[4] = 1

arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**4. Create a vector with values ranging from 10 to 49**

In [5]:
arr = np.arange(10, 50)

arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**5. Create a 3x3 matrix with values ranging from 0 to 8**

In [6]:
arr = np.arange(0, 9)
mt = arr.reshape(3, 3)

mt

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**6. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [7]:
arr = np.array([1,2,0,0,4,0])

np.nonzero(arr)

(array([0, 1, 4]),)

**7. Create a 3x3 identity matrix**

In [8]:
arr = np.eye(3)

arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**8. Create a 3x3x3 array with random values**

In [9]:
arr = np.random.random((3, 3))

arr

array([[0.58558688, 0.01001567, 0.59981359],
       [0.64967225, 0.2166347 , 0.40849001],
       [0.94632269, 0.94595991, 0.26356627]])

**9. Create a 10x10 array with random values and find the minimum and maximum values**

In [10]:
arr = np.random.random((10, 10))

print(np.min(arr))
print(np.max(arr))

0.024440157890954883
0.9824880529219735


**10. Create a random vector of size 30 and find the mean value**

In [11]:
vec = np.random.random(30)

np.mean(vec)

0.5173281538412275

**11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [12]:
np.diag([1, 2, 3, 4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**12. Normalize a 5x5 random matrix**

In [13]:
mt = np.random.random((5, 5))
normalized = (mt - np.mean(mt)) / np.std(mt)

print(mt)
print(normalized)

[[0.69607151 0.48998825 0.24780944 0.34766045 0.35499118]
 [0.70730663 0.23415507 0.57113437 0.79680667 0.68971314]
 [0.73401513 0.18097136 0.49629146 0.46768926 0.93251888]
 [0.2088738  0.24490518 0.32800137 0.78666951 0.70061111]
 [0.13968448 0.0478209  0.39678166 0.48775324 0.23900142]]
[[ 0.98908716  0.12164249 -0.89773539 -0.47744299 -0.44658653]
 [ 1.03637797 -0.95520927  0.46320234  1.41310111  0.96232356]
 [ 1.14879925 -1.17906989  0.14817397  0.02778172  1.9843403 ]
 [-1.06162307 -0.90995995 -0.56019189  1.37043183  1.00819523]
 [-1.35285444 -1.73952616 -0.27068222  0.1122349  -0.93481004]]


**13. How to find common values between two arrays?**

In [14]:
arr1 = np.arange(1, 10)
arr2 = np.arange(5, 15)

np.intersect1d(arr1, arr2)

array([5, 6, 7, 8, 9])

**14. Create a random vector of size 10 and sort it**

In [15]:
vec = np.random.random(10)
np.sort(vec)


array([0.16272223, 0.16574747, 0.21799502, 0.37716795, 0.49953909,
       0.76670459, 0.81099773, 0.89568657, 0.90899869, 0.91773759])

**15. Create random vector of size 10 and replace the maximum value by 0**

In [16]:
vec = np.random.random(10)
vec


array([0.72098238, 0.04726804, 0.58471496, 0.76411127, 0.46587328,
       0.74968058, 0.81951319, 0.40507876, 0.98793966, 0.43852703])

In [17]:
vec[np.argmax(vec)] = 0
vec


array([0.72098238, 0.04726804, 0.58471496, 0.76411127, 0.46587328,
       0.74968058, 0.81951319, 0.40507876, 0.        , 0.43852703])

**16. Subtract the mean of each row of a matrix**

In [18]:
arr = np.arange(1, 10).reshape(3, 3)

print(arr)
np.mean(arr, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [19]:
mean = np.mean(arr, axis=1, keepdims=True)
print(mean)

[[2.]
 [5.]
 [8.]]


In [20]:
subtracted = arr - mean
subtracted

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

**17. How to get the n largest values of an array**

In [21]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5

In [22]:
#np.sort

sorted = np.sort(arr)

print(sorted[-n:])


[9995 9996 9997 9998 9999]


In [23]:
#np.argsort

sorted_indices = np.argsort(arr)
n_largest = arr[sorted_indices[-n:]]

print(n_largest)


[9995 9996 9997 9998 9999]


In [24]:
#np.argpartition

sorted_indices = np.argpartition(arr, range(len(arr)))
n_largest = arr[sorted_indices[-n:]]

print(n_largest)


[9995 9996 9997 9998 9999]


**18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36)**

In [25]:
mt = np.arange(1, 16).reshape(5, 3)
np.random.shuffle(mt)

mt

array([[ 4,  5,  6],
       [ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [26]:
np.where(mt <= 4, mt, mt**2)

array([[  4,  25,  36],
       [  1,   2,   3],
       [ 49,  64,  81],
       [100, 121, 144],
       [169, 196, 225]])